[project]
name = "pattern-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "matplotlib>=3.5.0",
    "scikit-learn>=1.3.0",
    "scikit-learn-extra>=0.2.0",
]
